test:
  # ???????????
  login:
    username: username
    password: password
  server:
    # ?????????
    record:
      url: http://localhost:9050
    task:
      url: http://localhost:8081
    # ?????????
    auth:
      url: http://localhost:9000

spring:
  main:
    allow-bean-definition-overriding: true

