test:
  # ???????????
  login:
    username: username
    password: password
  server:
    # ?????????
    record:
      url: http://localhost/api
    task:
      url: http://localhost/api
    # ?????????
    auth:
      url: http://localhost

spring:
  main:
    allow-bean-definition-overriding: true

